name: yopp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+109

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  url_launcher: ^6.0.9
  shared_preferences: ^2.0.6

  badges: ^2.0.1
  country_list_pick: ^1.0.1+2
  
 
  pin_code_fields: ^7.3.0
  flutter_switch: ^0.3.2

  flutter_svg: ^0.22.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  

  flutter_pdfview: ^1.0.4
  path_provider: ^2.0.2
  image_picker: ^0.8.3+2
  permission_handler: ^8.1.4+2
  cached_network_image: ^3.1.0
  pull_to_refresh: ^2.0.0

  tcard: ^1.2.2

  firebase_core: ^1.4.0
  firebase_analytics: ^8.2.0
  firebase_crashlytics: ^2.1.1
  firebase_performance: ^0.7.0+7
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1
  firebase_messaging: ^10.0.4
  firebase_database: ^7.1.2
  flutter_local_notifications: ^8.1.1+1
  flutter_app_badger: ^1.2.0
 
  flutter_sim_country_code: ^0.1.1

  geolocator: ^7.4.0
  geocoder: ^0.2.1

  
  flutter_bloc: ^7.1.0
  equatable: ^2.0.3

  flutter_libphonenumber: ^1.1.0

  timeago: ^3.1.0
  intl: ^0.17.0
  mailto: ^2.0.0

  simple_animations: ^3.1.1
  grouped_buttons: ^1.0.4
  rename: ^1.2.0

  image_cropper: ^1.3.1

  flutter_slidable: ^0.6.0
  
  socket_io_client: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.jpeg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/onboarding/
    - assets/sports/
    - assets/sports/golf.svg
    - assets/documents/license.txt
    - assets/documents/privacy_policy.pdf
    - assets/documents/terms.pdf
    - assets/documents/faq.pdf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Euphemia
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf
       

         

      
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
